package com.rick.recoveryapp.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.rick.recoveryapp.greendao.entity.PowerAVG;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POWER_AVG".
*/
public class PowerAVGDao extends AbstractDao<PowerAVG, Long> {

    public static final String TABLENAME = "POWER_AVG";

    /**
     * Properties of entity PowerAVG.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RecordID = new Property(1, String.class, "RecordID", false, "RECORD_ID");
        public final static Property LeftAvg = new Property(2, String.class, "LeftAvg", false, "LEFT_AVG");
        public final static Property RightAvg = new Property(3, String.class, "RightAvg", false, "RIGHT_AVG");
    }


    public PowerAVGDao(DaoConfig config) {
        super(config);
    }
    
    public PowerAVGDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POWER_AVG\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"RECORD_ID\" TEXT," + // 1: RecordID
                "\"LEFT_AVG\" TEXT," + // 2: LeftAvg
                "\"RIGHT_AVG\" TEXT);"); // 3: RightAvg
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POWER_AVG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PowerAVG entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String RecordID = entity.getRecordID();
        if (RecordID != null) {
            stmt.bindString(2, RecordID);
        }
 
        String LeftAvg = entity.getLeftAvg();
        if (LeftAvg != null) {
            stmt.bindString(3, LeftAvg);
        }
 
        String RightAvg = entity.getRightAvg();
        if (RightAvg != null) {
            stmt.bindString(4, RightAvg);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PowerAVG entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String RecordID = entity.getRecordID();
        if (RecordID != null) {
            stmt.bindString(2, RecordID);
        }
 
        String LeftAvg = entity.getLeftAvg();
        if (LeftAvg != null) {
            stmt.bindString(3, LeftAvg);
        }
 
        String RightAvg = entity.getRightAvg();
        if (RightAvg != null) {
            stmt.bindString(4, RightAvg);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PowerAVG readEntity(Cursor cursor, int offset) {
        PowerAVG entity = new PowerAVG( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // RecordID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // LeftAvg
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // RightAvg
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PowerAVG entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRecordID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLeftAvg(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRightAvg(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PowerAVG entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PowerAVG entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PowerAVG entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
